workflows:
  ios-workflow:
    name: iOS IPA build
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Flutter precache
        script: flutter precache --ios

      - name: Flutter clean
        script: flutter clean

      - name: Get packages
        script: flutter pub get

      - name: Install pods
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          pod repo update
          pod install --repo-update
          cd ..

      - name: Build IPA
        script: flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa