workflows:
  ios-workflow:
    name: iOS IPA build
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Enter Flutter project
        script: |
          cd Clouvex_Project
          flutter clean
          flutter pub get

      - name: Build IPA
        script: |
          cd Clouvex_Project
          flutter build ipa --release --no-codesign

    artifacts:
      - Clouvex_Project/build/ios/ipa/*.ipa